[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
    -DSECRETS_FILE=\"secrets.h\"
    -I.

lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
    links2004/WebSockets@^2.4.1
    kmackay/micro-ecc@^1.0.0

